namespace TathamOddie.RegexAnalyzer.Logic.Tokens
{
    public enum TokenType
    {
        ParseFailure,
        Literal,
        GroupStart,
        GroupEnd,
        GroupDirectiveStart,
        GroupOption,
        GroupOptionQualifier,
        GroupOptionEnd,
        NamedIdentifierStart,
        NamedIdentifierEnd,
        NonCapturingGroupMarker,
        Quantifier,
        StartOfStringAssertion,
        EndOfStringAssertion,
        PositiveLookAheadMarker,
        NegativeLookAheadMarker,
        ConditionalExpressionStart,
        ConditionalExpressionEnd,
        OrOperator,
        CharacterEscapeMarker,
        CharacterEscapeData,
        CharacterSetStart,
        CharacterSetEnd,
        NegativeCharacterSetModifier,
        ParametizedQuantifierStart,
        ParametizedQuantifierEnd,
        Number,
        ParametizedQuantifierRangeSeparator
    }
}